 {/*IMPORTANT:  layout file is converted to .jsx because TypeScript support is not polished yet*/}

import './globals.css'
import Nav from './auth/Nav'
import QueryWrapper from './auth/QueryWrapper'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96`}>
       
        {/* wrap with a react query component */}
        <QueryWrapper>
          <Nav/>
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
